language: node_js
node_js:
- '7'
script:
- yarn test-travis
addons:
  ssh_known_hosts:
  - 54.254.158.105
  - 13.228.71.129
before_install:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then openssl aes-256-cbc -K $encrypted_9d3fc0282286_key -iv $encrypted_9d3fc0282286_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then eval "$(ssh-agent -s)"; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then chmod 600 /tmp/deploy_rsa; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ssh-add /tmp/deploy_rsa; fi
deploy:
- provider: script
  skip_cleanup: true
  script: yarn build-src
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: rsync -aqr --delete $TRAVIS_BUILD_DIR/build/. Administrator@54.254.158.105:/cygdrive/c/inetpub/wwwroot
  on:
    branch: staging
